//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieez.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CinemaCity_QueryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CinemaCity_QueryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieez.Resources.CinemaCity_QueryStrings", typeof(CinemaCity_QueryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd[role=&apos;menuitem&apos;].
        /// </summary>
        internal static string boxList {
            get {
                return ResourceManager.GetString("boxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul li a.
        /// </summary>
        internal static string dateBoxSearchList {
            get {
                return ResourceManager.GetString("dateBoxSearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;row movie-about&apos;].
        /// </summary>
        internal static string info_div {
            get {
                return ResourceManager.GetString("info_div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;sivug&apos;].
        /// </summary>
        internal static string info_div_inner {
            get {
                return ResourceManager.GetString("info_div_inner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string inner_metadata {
            get {
                return ResourceManager.GetString("inner_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[id^=&apos;movie-wrapper&apos;].
        /// </summary>
        internal static string loadedMovies {
            get {
                return ResourceManager.GetString("loadedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;siteinfo&apos;] span:first-of-type.
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;col-lg-4 movie-slider-page-img&apos;] img[class=&apos;img-fluid&apos;].
        /// </summary>
        internal static string MainImage {
            get {
                return ResourceManager.GetString("MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .activ a.
        /// </summary>
        internal static string movieUrl {
            get {
                return ResourceManager.GetString("movieUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div a[alt=&apos;open chatbot&apos;] div.
        /// </summary>
        internal static string openBotButton {
            get {
                return ResourceManager.GetString("openBotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;tak&apos;].
        /// </summary>
        internal static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;sidebar&apos;] div[class=&apos;selectionInfo&apos;].
        /// </summary>
        internal static string screeningMetadataContainer {
            get {
                return ResourceManager.GetString("screeningMetadataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul li a.
        /// </summary>
        internal static string screeningTimes {
            get {
                return ResourceManager.GetString("screeningTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dl dt a.
        /// </summary>
        internal static string searchBoxes {
            get {
                return ResourceManager.GetString("searchBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div div a.
        /// </summary>
        internal static string theaterPageLink {
            get {
                return ResourceManager.GetString("theaterPageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;wide-menu-wrapper&apos;] div[class=&apos;row locations-grid&apos;] div[class$=&apos;loc-wrapper&apos;].
        /// </summary>
        internal static string theaters {
            get {
                return ResourceManager.GetString("theaters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul li a.
        /// </summary>
        internal static string theaterSearchBoxList {
            get {
                return ResourceManager.GetString("theaterSearchBoxList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div h1[class$=&apos;title&apos;].
        /// </summary>
        internal static string tmpMovieName {
            get {
                return ResourceManager.GetString("tmpMovieName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;siteinfo&apos;] span:nth-of-type(2).
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
    }
}
