//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieez.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HotCinema_QueryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HotCinema_QueryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieez.Resources.HotCinema_QueryStrings", typeof(HotCinema_QueryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[1]/img.
        /// </summary>
        internal static string AddMoviePicture_elem {
            get {
                return ResourceManager.GetString("AddMoviePicture_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[1]/div[2]/span.
        /// </summary>
        internal static string durationOfMovie {
            get {
                return ResourceManager.GetString("durationOfMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/h2.
        /// </summary>
        internal static string englishName {
            get {
                return ResourceManager.GetString("englishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[2].
        /// </summary>
        internal static string movieDirectorAndCast {
            get {
                return ResourceManager.GetString("movieDirectorAndCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[1]/div[1]/span.
        /// </summary>
        internal static string movieGenre {
            get {
                return ResourceManager.GetString("movieGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[2]/div[2]/span.
        /// </summary>
        internal static string movieRating {
            get {
                return ResourceManager.GetString("movieRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[2]/iframe.
        /// </summary>
        internal static string MovieTrailer {
            get {
                return ResourceManager.GetString("MovieTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/h1.
        /// </summary>
        internal static string nameOfMovie {
            get {
                return ResourceManager.GetString("nameOfMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[1]/div/div/div[1]/div[3]/div[1]/div[2]/div[2].
        /// </summary>
        internal static string ParseAllMovies_elem2 {
            get {
                return ResourceManager.GetString("ParseAllMovies_elem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div/div[2]/div/div/div/div/table/tbody.
        /// </summary>
        internal static string ParseScreening_elem1 {
            get {
                return ResourceManager.GetString("ParseScreening_elem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div/div[4]/div[2]/div.
        /// </summary>
        internal static string parseTheaters_elem {
            get {
                return ResourceManager.GetString("parseTheaters_elem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[1]/div/div/div[1]/div[3]/div[2]/div[2].
        /// </summary>
        internal static string parseTheaters_elem2 {
            get {
                return ResourceManager.GetString("parseTheaters_elem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1].
        /// </summary>
        internal static string plot {
            get {
                return ResourceManager.GetString("plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[3]/div[2]/div[1]/span.
        /// </summary>
        internal static string ReleaseDateOfMovie {
            get {
                return ResourceManager.GetString("ReleaseDateOfMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html/body/div[2]/div[4]/div[1]/div/div/div/div[2]/h1.
        /// </summary>
        internal static string theatherName {
            get {
                return ResourceManager.GetString("theatherName", resourceCulture);
            }
        }
    }
}
