//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movieez.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class YesPlanet_QueryStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal YesPlanet_QueryStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movieez.Resources.YesPlanet_QueryStrings", typeof(YesPlanet_QueryStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[data-automation-id=&apos;poster-link&apos;].
        /// </summary>
        internal static string allMoviesElements {
            get {
                return ResourceManager.GetString("allMoviesElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-automation-id^=&apos;day_&apos;]:not([disabled=&apos;disabled&apos;]).
        /// </summary>
        internal static string daysFilterButtons {
            get {
                return ResourceManager.GetString("daysFilterButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dt[class=&apos;tbl-cell-ttl ttl&apos;] + dd.
        /// </summary>
        internal static string innerMetadataContainer {
            get {
                return ResourceManager.GetString("innerMetadataContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div div[class=&apos;loaded&apos;].
        /// </summary>
        internal static string isMovieActive {
            get {
                return ResourceManager.GetString("isMovieActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;pt-none pb-none&apos;].
        /// </summary>
        internal static string isMoviePlaying {
            get {
                return ResourceManager.GetString("isMoviePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul[class=&apos;qb-movie-attributes&apos;] &gt; li &gt; span.
        /// </summary>
        internal static string langElements {
            get {
                return ResourceManager.GetString("langElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button[class=&apos;btn btn-grey btn-block text-center&apos;].
        /// </summary>
        internal static string loadMoreMoviesButton {
            get {
                return ResourceManager.GetString("loadMoreMoviesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p[class=&apos;info-descr&apos;].
        /// </summary>
        internal static string movieDurationElement {
            get {
                return ResourceManager.GetString("movieDurationElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h1[class=&apos;upper-case&apos;].
        /// </summary>
        internal static string movieNameElement {
            get {
                return ResourceManager.GetString("movieNameElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text-content.
        /// </summary>
        internal static string moviePlotElement {
            get {
                return ResourceManager.GetString("moviePlotElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p[class=&apos;info-descr&apos;].
        /// </summary>
        internal static string movieReleaseDateElement {
            get {
                return ResourceManager.GetString("movieReleaseDateElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[data-automation-id=&apos;play-trailer-button&apos;].
        /// </summary>
        internal static string movieTrailerElement {
            get {
                return ResourceManager.GetString("movieTrailerElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to img[class^=&apos;img-responsive poster&apos;].
        /// </summary>
        internal static string PosterImage {
            get {
                return ResourceManager.GetString("PosterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;calendar-widget&apos;] h5.
        /// </summary>
        internal static string screeningDate {
            get {
                return ResourceManager.GetString("screeningDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class$=&apos;type-row&apos;].
        /// </summary>
        internal static string screeningsContainer {
            get {
                return ResourceManager.GetString("screeningsContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select[class=&apos;form-control qb-selectpicker&apos;].
        /// </summary>
        internal static string screeningsFilterElements {
            get {
                return ResourceManager.GetString("screeningsFilterElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;qb-movie-info-column&apos;] &gt; a[class=&apos;btn btn-primary btn-lg&apos;]:not([aria-label=&apos;Manage Cookies&apos;]).
        /// </summary>
        internal static string screeningTimesElements {
            get {
                return ResourceManager.GetString("screeningTimesElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul[class=&apos;qb-screening-attributes&apos;] span[aria-label^=&apos;Screening type:&apos;].
        /// </summary>
        internal static string screeningTypeElements {
            get {
                return ResourceManager.GetString("screeningTypeElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-id=&apos;select12&apos;].
        /// </summary>
        internal static string screeningTypeFilterBoxElement {
            get {
                return ResourceManager.GetString("screeningTypeFilterBoxElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-automation-id^=&apos;day_&apos;]:not([disabled=&apos;disabled&apos;]).
        /// </summary>
        internal static string screeningTypeFilterBoxListElements {
            get {
                return ResourceManager.GetString("screeningTypeFilterBoxListElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;row movie-row first-movie-row&apos;] p.
        /// </summary>
        internal static string theaterAddress {
            get {
                return ResourceManager.GetString("theaterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button[data-id=&apos;select11&apos;].
        /// </summary>
        internal static string theaterFilterBoxElement {
            get {
                return ResourceManager.GetString("theaterFilterBoxElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[class=&apos;selectpicker-dropdown-container npm-quickbook&apos;] li.
        /// </summary>
        internal static string theaterFilterBoxListElements {
            get {
                return ResourceManager.GetString("theaterFilterBoxListElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qb-cinema-name.
        /// </summary>
        internal static string theaterName {
            get {
                return ResourceManager.GetString("theaterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul[class=&apos;dropdown-menu inner&apos;] li a.
        /// </summary>
        internal static string theatersElements {
            get {
                return ResourceManager.GetString("theatersElements", resourceCulture);
            }
        }
    }
}
